In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import NMF, LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.sklearn
import pyLDAvis.gensim
import numpy as np
from datetime import datetime, date, time
import csv
import sys
import importlib
import pandas as pd

In [2]:
def tf_vctorize(n_max_features, text):
    #n_features = 1000
    tf_vectorizer = CountVectorizer(strip_accents = 'unicode',
                                max_features=n_max_features,
                                stop_words='english',
                                max_df = 0.95,
                                min_df = 2)
    tf = tf_vectorizer.fit_transform(text)
    tf_feature_names = tf_vectorizer.get_feature_names()
    return tf, tf_vectorizer, tf_feature_names
    

def LDA_analyze(tf_vector, n_topics):
    lda = LatentDirichletAllocation(n_topics=n_topics,doc_topic_prior =1/(n_topics*10), max_iter=50,
                                learning_method='online',
                                learning_offset=50.,
                                evaluate_every = 1,
                                random_state=0)
    lda.fit(tf_vector)
    print(lda)
    return lda

def tf_idf(n_max_features, text):
    tfidf_vectorizer = TfidfVectorizer(max_df=0.95,
                                       min_df=2,
                                       max_features=n_max_features,
                                       stop_words='english')
    tfidf = tfidf_vectorizer.fit_transform(text)
    tfidf_feature_names = tfidf_vectorizer.get_feature_names()
    return tfidf, tfidf_feature_names


In [3]:
data = pd.read_csv('"urban vitality".csv', names = 'abcdef')

In [4]:
#data['e'].head(20)

In [5]:
#from nltk.corpus import wordnet

In [6]:
data['e'] = data['c'].replace(r'http\S+|http', '', regex=True).replace(r'www\S+|WWW\S+|www', '', regex=True)
data['e'] = data['e'].str.lower().str.replace('skip to main content|skip to article|skip to content|main menu|page', '')
data['e'] = data['e'].str.replace(r'[\W_]+',' ')
data['e'] = data['e'].str.replace(r'\d+',' ')
data['e'] = data['e'].str.replace(r'\b(\w)\b', '')
data['e'] = data['e'].replace(np.nan, '', regex=True)
data['e'] = data['e'].apply(str)
#print(data['e'])


Len = len(data['e'])
print(Len)
#print(data.iloc[0:5,4:5])
index_group = []
for index, row in data.iterrows():
    s =row[4]
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        index_group.append(index)
    else:
        continue
    #print(data['e'][1])
    #s =data.iloc[j]['e']
    #isEnglish = s.encode(encoding='utf-8').decode('ascii')
    #print(isEnglish)
    #if not wordnet.synsets(data.iloc[j]['e']):#Comparing if word is non-English
        #print(data.iloc[j]['e'])
        #data.drop(j, inplace=True)

3773


In [7]:
data.drop(index_group, inplace=True)

In [8]:
len(data['e'])

3491

In [9]:
print(index_group)

[30, 73, 134, 597, 790, 792, 848, 904, 948, 957, 964, 1029, 1412, 1414, 1419, 1427, 1434, 1441, 1443, 1449, 1453, 1457, 1458, 1459, 1460, 1462, 1464, 1470, 1473, 1475, 1530, 1536, 1588, 1596, 1645, 1646, 1648, 1651, 1653, 1654, 1666, 1674, 1678, 1686, 1688, 1694, 1708, 1712, 1720, 1732, 1904, 1906, 1919, 1920, 1922, 1923, 1924, 1930, 1980, 1982, 1986, 1987, 1998, 1999, 2002, 2006, 2010, 2068, 2081, 2127, 2128, 2134, 2146, 2160, 2168, 2169, 2170, 2171, 2174, 2176, 2181, 2192, 2208, 2210, 2231, 2243, 2244, 2245, 2246, 2247, 2259, 2264, 2280, 2397, 2403, 2407, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2425, 2433, 2436, 2438, 2440, 2443, 2455, 2458, 2461, 2472, 2477, 2489, 2497, 2510, 2517, 2580, 2609, 2657, 2669, 2672, 2690, 2693, 2694, 2695, 2696, 2702, 2703, 2704, 2708, 2709, 2710, 2713, 2714, 2715, 2731, 2732, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2747, 2750, 2754, 2757, 2760, 2765, 2777, 2778, 2782, 2787, 2789, 2816, 2824, 2837, 2839, 2840, 2842, 2844, 2845, 2847

In [10]:
data['e'].to_csv('after_clean7.csv')

In [11]:
#data_language = data['e']
#text_all = data_language.tolist()
#print(text_all[0:2])

In [12]:
data_new = data['e']

In [13]:
text_all = data_new.tolist()
print(text_all[0:3])

[' book  the renaissance  history of civilization in italy from     ad', ' html html towards  positive local government policy for residential rehabilitation', ' pdf pdf systems of urban growth ']


In [14]:
n_max_features=3000
n_topics = 10
n_top_words = 10

tf_vector, tf_vectorizer, tf_feature_names = tf_vctorize(n_max_features, text_all)
lda = LDA_analyze(tf_vector, n_topics)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:314: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=0.01,
             evaluate_every=1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=None, n_topics=10, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)


In [ ]:
#tfidf, tfidf_feature_names = tf_idf(n_max_features, text_all)
pyLDAvis.enable_notebook()
lda_prepared = pyLDAvis.sklearn.prepare(lda, tf_vector, tf_vectorizer, R=20)
pyLDAvis.show(lda_prepared)


Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [16/Aug/2019 20:26:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2019 20:26:44] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2019 20:26:44] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2019 20:26:45] "GET /LDAvis.js HTTP/1.1" 200 -


In [16]:
print(lda_prepared)

PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
3      81.636049        1       1 -0.086795 -0.051051
7       7.408662        1       2 -0.216661  0.092731
1       4.003516        1       3  0.101290  0.186036
0       2.105210        1       4 -0.044603 -0.074050
2       1.452494        1       5  0.081438 -0.029212
5       1.207190        1       6  0.031902 -0.028464
8       0.598750        1       7  0.035711 -0.021016
6       0.598153        1       8  0.034137 -0.025976
4       0.561848        1       9  0.037109 -0.024882
9       0.428127        1      10  0.026470 -0.024117, topic_info=     Category         Freq           Term        Total  loglift  logprob
term                                                                    
2855  Default  1337.000000          urban  1337.000000  20.0000  20.0000
2921  Default   972.000000       vitality   972.000000  19.0000  19.0000
1738  Default   1

In [253]:
N=10
for i in lda_prepared[3:]:
    #i.shape()
    print(i)
    N+=1
    #i.to_csv("output"+ str(N) +'.csv')

30
0.01
{'xlab': 'PC1', 'ylab': 'PC2'}
[10, 6, 1, 8, 4, 9, 7, 2, 3, 5]


In [237]:
for topic_idx, topic in enumerate(lda.components_):
    print("Topic #%d:" % topic_idx)
    #print(topic)
    print(topic.argsort()[-10:-1])
    #print(topic.argsort()[:-n_top_words - 1:-1])
    #print(tf_feature_names)
    

Topic #0:
[279 126 122 258  73 257 174 182  36]
Topic #1:
[ 30 277 105 210 193 149  52 201 197]
Topic #2:
[169  76  68  13  52  12 194  16  17]
Topic #3:
[ 39  80 283  57 205  59 197 111 179]
Topic #4:
[216 187 262 209  55  19  42 133 129]
Topic #5:
[279 126 122 258  73 257 174 182  36]
Topic #6:
[ 30 277 105 210 193 149  52 201 197]
Topic #7:
[ 57 133 137  42 274  35 197 179  24]
Topic #8:
[237 163  36 122 241 124 257  10 184]
Topic #9:
[135  19  24  66 297 163 279  55  58]


In [183]:
print(tf_feature_names)

['00', '000', '10', '1000', '1080', '1085', '10th', '11', '1100', '1145', '11th', '12', '12th', '14th', '15', '15th', '17th', '19th', '1st', '20', '20th', '30', '3pm', '900', 'able', 'absolute', 'absolutely', 'access', 'accessible', 'according', 'acoustics', 'action', 'activities', 'actually', 'addition', 'adjacent', 'admire', 'admission', 'adults', 'afternoon', 'age', 'ages', 'ago', 'air', 'alike', 'alive', 'allow', 'allowed', 'altar', 'alter', 'amazing', 'amazingly', 'ambience', 'ancient', 'anytime', 'app', 'appreciate', 'april', 'arch', 'architectural', 'architecture', 'area', 'areas', 'array', 'arrived', 'art', 'artifacts', 'ask', 'asked', 'aspects', 'assembled', 'astrological', 'astronomic', 'astronomical', 'atmosphere', 'attached', 'attended', 'attraction', 'attractions', 'attractive', 'august', 'aula', 'austere', 'authentic', 'autumn', 'available', 'away', 'awe', 'awesome', 'baby', 'bar', 'basement', 'basic', 'basis', 'bathrooms', 'beatiful', 'beautiful', 'beautifull', 'beautifu

In [239]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-30 - 1:-1]]))
    print()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
lund buildings old museum sweden different swedish history houses visit time place interesting kulturen day trip really cathedral people outside went house exhibits times life culture small visited lived exhibitions
Topic #1:
kids place playground children liked peaceful really fun various bit enjoyed exhibits denmark great area going especially love caf outdoor old set fantastic perfect took season beauty summer amazing way
Topic #2:
exhibition art areas people april children architectural dating early medieval religious noon different lund day crypt visited huge beautiful visit nice center church old fascinating cathedral interesting museum small century
Topic #3:
park nice good place close pond city walk enjoy cafe recommended people lund children little birds relax students coffee located miss day town outdoor play weather stadsparken look easily sunny
Topic #4:
clock impressive inside cathedral astronomical church read time outside religious giant town basement visit wal